### ISSUE TITLE
Integrate user activity with front page

### ISSUE THREAD

**Issue by Kogni** [bitraf/p2k16#19]
The activity graph on bitraf.no doesn't show any activity from p2k16, so Bitraf looks dead to new people.

**Comment by tingox** [comment]
Are we supposed to see a graph (or anything at all) on that URL in staging?
Currently (2018-05-23, at 12:48 local time) nothing shows up.

**Comment by trygvis** [comment]
It is kinda boring if nobody has logged in, I'll give you that. This has been rolled out in production now: https://p2k16.bitraf.no/frontpage-graph.

**Comment by Kogni** [comment]
That graph looks good, but it's not the graph that shows on the front page.

**Comment by tingox** [comment]
The frontpage currently uses
`https://p2k12.bitraf.no/chart.php` in an iframe element
somebody probably needs to change that.

**Comment by odinho** [comment]
Updated website. Looks good again :D
