### ISSUE TITLE
User links don't work on log events with badges

### ISSUE THREAD

**Issue by Kogni** [bitraf/p2k16#20]
In the log for "Recent events", the link to users' public pages isn't always correct. 
Whenever the log event includes a badge, the link in the user name refers to https://p2k16.bitraf.no/#!/ instead of the user's public page.

![image](https://user-images.githubusercontent.com/15120598/39866644-bf3f06d4-5451-11e8-9039-33fad4f8cdb1.png)

**Comment by omega** [comment]
This was also fixed in the #42 / #50 messy merging.

**Comment by jenschr** [comment]
Sure, but I don't think it's out yet?

**Comment by omega** [comment]
It's not, but just noting it down for closing in the  future when it is out :)

**Comment by omega** [comment]
This has now been released it seems
