### ISSUE TITLE
Support other membership types

### ISSUE THREAD

**Issue by jenschr** [bitraf/p2k16#22]
Bitraf has 3 primary types of members:
- Normal member (Stripe)
- Coworkers (monthly invoice)
- Sponsors (annual invoice)

These are all members, but they pay their membership differently. Normal members are fully covered in P2K16, but not the other two member types.

The current solution is to add these users manually, but this is problematic since we do no know what users are connected to what firms. We almost did an error on this, but Google helped tell us that the person we thought had the wrong status was indeed connected through an existing sponsor.

**Comment by haavares** [comment]
Companies and connected users can be updated at the admin page of p2k16.

Connected users automatically receive door access without being in the door circle.
