### ISSUE TITLE
Door opening not working on billing day

### ISSUE THREAD

**Issue by jonnor** [bitraf/p2k16#24]
Steps to reproduce

* Have an account with payment due sometimes today (but not yet attempted)
* Try to open door

Expected

* Can open door successfully

Actual

* Unable to open door. "Account does not have active membership"

**Comment by jonnor** [comment]
Seem that the logic for checking membership is a little bit wrong. Maybe because end_date is always set to someday@00.00 (unverified), and then payment is not attempted until sometime later that day.

Proposed solution: Allow 24 hour extra grace period when checking membership status

**Comment by haavares** [comment]
Fixed in a69ff7c5149dc3b91dc85ea13b444de12a37b587
