### ISSUE TITLE
Become a paying Bitraf member is always shown

### ISSUE THREAD

**Issue by Kogni** [bitraf/p2k16#29]
"Become a paying Bitraf member
Set a credit card and select membership level to become a paying member.
You will receive access to open the door 24/7 and access machines at Bitraf."

This text is showing to members who already have a subscription running. This can be confusing and cause misunderstandings.

**Comment by jonnor** [comment]
https://github.com/bitraf/p2k16/pull/42 should fix this

**Comment by nikolai-kolstad** [comment]
This issue has been fixed
