### ISSUE TITLE
Usernames containing a space cannot be added to circles

### ISSUE THREAD

**Issue by jenschr** [bitraf/p2k16#32]
Adding the user "Mir Karim" to the Door circle is not possible. Produces error:

    Got unexpected error from database. Probably some constraint was broken.

**Comment by trygvis** [comment]
The user was added by you at 16:24:39 and the later attempts gave the error message. I blame bad UI and a bad check in the code that should check for existing membership.

**Comment by jenschr** [comment]
I used a phone and I could not find the user in the list after adding the first time. The following times I tried, I got the standard error. Brilliant with a clear message!
