### ISSUE TITLE
Contextual content on front page 

### ISSUE THREAD

**Issue by nikolai-kolstad** [bitraf/p2k16#41]
If possible, when logged in, the content on the front page https://p2k16.bitraf.no/#!/ should vary wether you are a paying member or not. 

• Paying members should not see the "Become a paying Bitraf member" text.
• Non paying members should not see the door opening buttons.

**Comment by jonnor** [comment]
Agreed. Suggesting also that new members that are not in door-circle get a helpful messsge, ala:

"Thanks for becoming a new Bitraf member.
To get access to unlocking the door, you must visit Bitraf such that one of the door admins can add you to the door circle. One of the regular build-night is a good time to go."

**Comment by omega** [comment]
this is attempted fixed in pr #42, but needs review, merge and release

**Comment by eliasbakken** [comment]
Who can review PR #42? @trygvis @jonnor ?

**Comment by jenschr** [comment]
I had a look through it. Looks solid, but needs testing since it's changing some core features (as turning "account" into "profile"). It's also hard to test the Stripe change without being on the real server?  I suggest merging and testing this on Staging.
