### ISSUE TITLE
Blank screen in Internet Explorer

### ISSUE THREAD

**Issue by jonnor** [bitraf/p2k16#53]
Someone used  Internet Explorer 42.17xxx and tried to access p2k16.bitraf.no - and only got a blank page

**Comment by omega** [comment]
Not sure this is the only error, and I didnt get a blank page when testing IE, but IE doesn't support `startsWith`, so this line fails at least:

https://github.com/bitraf/p2k16/blob/59f8026f7e6f34c33ffd41be95aac052c535fd60/web/src/p2k16/web/static/p2k16/p2k16.js#L191

**Comment by omega** [comment]
As a side-note, I end up seeing some data on the frontpage as if I was logged in:

* Buttons for unlocking doors (but the action of clicking is checking auth properly)
* Recent events (so I can see who has opened doors etc)

**Comment by omega** [comment]
Quite possibly easiest solution is polyfill: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith#Polyfill

**Comment by omega** [comment]
Fixed with polyfill
