### ISSUE TITLE
new functionality: delete or hide circles

### ISSUE THREAD

**Issue by tingox** [bitraf/p2k16#77]
background:
some circles have a wrongly spelled name - they should probably be deleted.
some circles is not in use anymore (example: modela-*) but we might want to keep the history.
some circles are more "important" than others (example: door*) and it should not be possible to delete them by a simple mistake.

functionality: a button or similar to delete or hide circles (if hide, we need a way to unhide also) with appropriate checks and warnings (do you really want to delete a circle with members in it?)

**Comment by nikolai-kolstad** [comment]
The relevant circles right now is :

Bitraf maintainence 
maximat-certified 
maximat-instructor 
modela-certified 
modela-instructor 
redsail-certified 
redsail-instructor
